### ISSUE TITLE
Loading

### ISSUE THREAD

**Issue by Dresch360** [sisimomo/MMM-NestRemoteThermostat#3]
Thank your for creating this great module!

I'm having an issue with the module just showing "Loading". I can't seem to find the issue and this is from the MM Log:
[21.11.2021 10:19.19.698] [LOG]   MMM-NestRemoteThermostat Node helper: Init notification received from module for thermostat "6416660000XXXXXX".
[21.11.2021 10:19.19.701] [LOG]   notification received.

Here the config.js code:
 {
 module: 'MMM-NestRemoteThermostat',
 position: 'top_right',
      config: {
        thermostatId: '6416660000XXXXXX',
        minValue: 50, // Minimum value for target temperature
        maxValue: 86, // Maximum value for target temperature
 targetTemperature: 72,
    ambientTemperature: 72,
    hvacState: "heating",
    fanSpeed: 3 // 0 to hide fan icon
      }
},

Any help would be greatly appreciated!

**Comment by sisimomo** [comment]
The "loading" state is set until a message with the property "loading" set to "false" has been sent to the module. Please refer to the section [Thermostat requirements and communication](https://github.com/sisimomo/MMM-NestRemoteThermostat#thermostat-requirements-and-communication). In addition, please note that it is essential to always set the property "loading" to "false" for each message, otherwise in some cases, the thermostat status will be automatically reset the property "loading" to "true".
