### ISSUE TITLE
Round to nearest whole number?

### ISSUE THREAD

**Issue by dathbe** [sisimomo/MMM-NestRemoteThermostat#4]
This is a beautiful module.  Thank you.
For those of us who live in countries that use Fahrenheit, it's not particularly necessary (and therefore cluttering) to display even .5 degree differences.  Is it possible to add an option to entirely remove the decimal place on the ambient and target temps and display the number rounded to the nearest whole?

**Comment by sisimomo** [comment]
Hi, I guess it wouldn't be hard to mark the "roundTargetTemperature" option as deprecated and introduce a new one that allows specifying the precision of the rounding. Unfortunately, I'm pretty busy with another project at the moment. However, if you're interested in helping out, feel free to go ahead! Otherwise, I'll look into it whenever I find some spare time.

The rounding fn could look something like this:
```js
function roundToPrecision(number, precision) {
    return  Math.round(number / precision) * precision;
}

const testCases = [
    { precision: 0.5, number: 4.82, expectedResult: 5 },
    { precision: 0.5, number: 4.7, expectedResult: 4.5 },
    { precision: 0.25, number: 4.82, expectedResult: 4.75 },
    { precision: 1, number: 4.51, expectedResult: 5 },
    { precision: 2, number: 3.1, expectedResult: 4 },
    { precision: 5, number: 2.6, expectedResult: 5 },
    { precision: 5, number: 2.4, expectedResult: 0 },
];

console.log(testCases.map(testCase => {
    const result = roundToPrecision(testCase.number, testCase.precision);
    return "Result match the expected result ? " + new String(result == testCase.expectedResult);
}));
```

**Comment by dathbe** [comment]
What if I change ```roundTargetTemperature``` and ```roundAmbientTemperature``` from boolean to string, with three options, ```tenth```, ```half```, or ```whole```?  I could build in backward compatibility to use ```tenth``` when "false" and ```half``` when "true".  This would effectively give a new option of "whole" for those of us who use Fahrenheit.

Alternatively, I could use a new variable called "roundWhole" (boolean) that would effectively override the two above variables.

Thoughts?

**Comment by sisimomo** [comment]
Making `roundTargetTemperature` and `roundAmbientTemperature` deprecated wouldn't stop users from using them; they would just no longer be included in the documentation.

We can introduce new options, `targetTemperaturePrecision` and `ambientTemperaturePrecision`, allowing users to select any desired precision.

The deprecated options, if set to true, would be equivalent to a precision of `0.5` in the new options.

I prefer this because it allows the user to have more control over the behavior of the module.

**Comment by dathbe** [comment]
I'll work on it.  I'm not great with javascript, and I'm just learning how to do PRs on GitHub, so it may take me a while.

**Comment by dathbe** [comment]
Well, after some trial and error I think I got it.
https://github.com/sisimomo/MMM-NestRemoteThermostat/pull/5
Testing appreciated.

In case it's not clear why it matters that you can round to any arbitrary number even though only one decimal will be displayed, here's what happens when you round 71.255:

0.1 = 71.3
0.2 = 71.2
0.25 = 71.3
0.5 = 71.5
1 = 71
2 = 72
